name: build windows x86, x64
on:
  push: {tags:  ['v*']} #  Push events to matching v*, i.e. v1.0, v20.15.10
  pull_request: 
  
permissions:
  contents: write

env:
  MINGWSDK: /opt/mingwsdk

jobs:
  build_mingw:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4

    - name: init enviroment
      run: |
        sudo apt-get -y install p7zip-full git make cmake
        curl -fsSL https://github.com/mstorsjo/llvm-mingw/releases/download/20240619/llvm-mingw-20240619-msvcrt-ubuntu-20.04-x86_64.tar.xz -o /tmp/llvm-mingw.tar.xz
        tar xf /tmp/llvm-mingw.tar.xz -C /tmp
        _tmppath=/tmp/llvm-mingw-20240619-msvcrt-ubuntu-20.04-x86_64 
        sudo mv -f ${_tmppath} $MINGWSDK
        chmod +x script/*.sh

    - name: build x86
      run: |
        mkdir build_mingw32
        export CC=${MINGWSDK}/bin/i686-w64-mingw32-clang
        export WINRES=${MINGWSDK}/bin/i686-w64-mingw32-windres
        export BUILD_DIR=$(pwd)/build_mingw32
        export BUILD_TYPE=MinSizeRel
        bash script/build_mingw.sh

    - name: build_x64
      run: |
        mkdir build_mingw64
        export CC=${MINGWSDK}/bin/x86_64-w64-mingw32-clang
        export WINRES=${MINGWSDK}/bin/x86_64-w64-mingw32-windres
        export BUILD_DIR=$(pwd)/build_mingw64
        export BUILD_TYPE=MinSizeRel
        bash script/build_mingw.sh
    
    - name: prepare release
      run: |
        mv build_mingw32/TileViewer.exe TileViewer_${{  github.ref_name }}_x86.exe
        mv build_mingw64/TileViewer.exe TileViewer_${{  github.ref_name }}_x64.exe
      
    - name: create release
      uses: ncipollo/release-action@v1
      if: github.event_name == 'push'
      with:
        artifacts: "TileViewer_*.exe"
        allowUpdates: "true"
        token: ${{ secrets.GITHUB_TOKEN }}