name: build linux
on:
  push: {tags:  ['v*']} #  Push events to matching v*, i.e. v1.0, v20.15.10
  pull_request: 
  
permissions:
  contents: write

jobs:
  build_linux_local:
    strategy:
      matrix: 
        arch: [{prefix: i386, suffix: x86}, {prefix: x86_64, suffix: x64}]

    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4

    - name: init enviroment
      run: |
        sudo apt-get -y install qemu-user-static binfmt-support
        sudo apt-get -y install p7zip-full git cmake

    - name: build ${{ matrix.arch.suffix }}
      run: |
        mkdir -p depend
        source script/fetch_depend.sh
        fetch_lua
        fetch_wxwidgets

        mkdir build
        export DOCKER_ARCH=${{ matrix.arch.prefix }}
        export BUILD_DIR=build
        export BUILD_TYPE=MinSizeRel
        bash script/build_docker.sh
    
    - name: prepare release
      run: |
        mv build/TileViewer TileViewer_${{  github.ref_name }}_${{ matrix.arch.suffix }}_linux
      
    - name: create release
      uses: ncipollo/release-action@v1
      if: github.event_name == 'push'
      with:
        artifacts: "TileViewer_*"
        allowUpdates: "true"
        token: ${{ secrets.GITHUB_TOKEN }}

  build_linux_cross:
    strategy:
      matrix: 
        arch: [{prefix: armhf, suffix: arm32}, {prefix: aarch64, suffix: arm64}]

    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4

    - name: init enviroment
      run: |
        sudo apt-get -y install qemu-user-static binfmt-support
        sudo apt-get -y install p7zip-full git cmake

    - name: build ${{ matrix.arch.suffix }}
      run: |
        mkdir -p depend
        source script/fetch_depend.sh
        fetch_lua
        fetch_wxwidgets
        
        mkdir build
        export DOCKER_ARCH=${{ matrix.arch.prefix }}
        export BUILD_DIR=build
        export BUILD_TYPE=MinSizeRel
        export USE_BUILDX=1
        bash script/build_docker.sh
    
    - name: prepare release
      run: |
        mv build/TileViewer TileViewer_${{  github.ref_name }}_${{ matrix.arch.suffix }}_linux
      
    - name: create release
      uses: ncipollo/release-action@v1
      if: github.event_name == 'push'
      with:
        artifacts: "TileViewer_*"
        allowUpdates: "true"
        token: ${{ secrets.GITHUB_TOKEN }}